DROP TABLE IF EXISTS `customer` CASCADE;

CREATE TABLE customer (
	`id` INT AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);